Added Java implementation
HowProgrammingWorks/RegExp pull request #1
Opened 2017-05-17 23:19 UTC by Seregy

2017-05-22 14:35 UTC, lundibundi requested changes
Just a few minor changes.

2017-05-22 14:35 UTC, lundibundi commented on Java/Match.java
> +        Matcher matcher1 = pattern.matcher(input1);
To make this more explicit and avoid duplicate code I'd suggest to put all inputs in a collection and then output results with something like
`input: result` or `'input': result`.

2017-05-22 14:35 UTC, lundibundi commented on Java/Split.java
> +        //Using String API
Missing space.

2017-05-22 14:36 UTC, lundibundi commented
Also @tshemsedinov I'd like match, replaceWithStringAPI, replaceWithRegexAPI etc to be separate functions in a single class file, but as we have separate files for JS example I'm not sure if this will be appropriate, what's your opinion on this?

2017-05-22 19:45 UTC, tshemsedinov commented
@lundibundi it is not a project but a set of examples, so we prepare them in separate files.
Also @Seregy please rename all files as I named them in JS version: `N-name.java` where N will be a number of example, it is good for sequential demonstration.

2017-05-22 19:46 UTC, tshemsedinov requested changes
Rename files

2017-05-27 18:33 UTC, Seregy commented
I've renamed files and made the necessary changes.

2017-05-27 18:42 UTC, lundibundi approved these changes
LGTM. Thanks for your effort.

2017-05-28 11:08 UTC, tshemsedinov approved these changes

2017-05-28 11:08 UTC, merged